. (Join-Path (Split-Path -Parent $PSScriptRoot) 'utils\engine.ps1')
Invoke-ZapretStrategyPrep
$bin = $script:ZapretBinDir
$lists = $script:ZapretListsDir
$gf = Get-ZapretGameFilter
$argList = @"
--wf-tcp=80,443,2053,2083,2087,2096,8443,$($gf.Tcp) --wf-udp=443,19294-19344,50000-50100,$($gf.Udp)
--filter-udp=443 --hostlist="$lists\list-general.txt" --hostlist="$lists\list-general-user.txt" --hostlist-exclude="$lists\list-exclude.txt" --hostlist-exclude="$lists\list-exclude-user.txt" --ipset-exclude="$lists\ipset-exclude.txt" --ipset-exclude="$lists\ipset-exclude-user.txt" --dpi-desync=fake --dpi-desync-repeats=11 --dpi-desync-fake-quic="$bin\quic_initial_www_google_com.bin" --new
--filter-udp=19294-19344,50000-50100 --filter-l7=discord,stun --dpi-desync=fake --dpi-desync-fake-discord="$bin\ACTIVE_DISCORD_UDP.bin" --dpi-desync-fake-stun="$bin\ACTIVE_DISCORD_UDP.bin" --dpi-desync-repeats=5 --new
--filter-tcp=2053,2083,2087,2096,8443 --hostlist-domains=discord.media --dpi-desync=fake,multisplit --dpi-desync-split-seqovl=681 --dpi-desync-split-pos=1 --dpi-desync-fooling=ts --dpi-desync-repeats=7 --dpi-desync-split-seqovl-pattern="$bin\tls_clienthello_www_google_com.bin" --dpi-desync-fake-tls="$bin\tls_clienthello_www_google_com.bin" --new
--filter-tcp=443 --hostlist="$lists\list-google.txt" --dpi-desync=hostfakesplit --dpi-desync-fooling=ts --dpi-desync-hostfakesplit-mod=host=www.google.com --new
--filter-tcp=80,443 --hostlist="$lists\list-general.txt" --hostlist="$lists\list-general-user.txt" --hostlist-exclude="$lists\list-exclude.txt" --hostlist-exclude="$lists\list-exclude-user.txt" --ipset-exclude="$lists\ipset-exclude.txt" --ipset-exclude="$lists\ipset-exclude-user.txt" --dpi-desync=fake,hostfakesplit --dpi-desync-fooling=ts --dpi-desync-hostfakesplit-mod=host=mail.ru,altorder=1 --dpi-desync-repeats=5 --dpi-desync-fake-tls="$bin\tls_clienthello_sochi_park.bin" --dpi-desync-fake-tls="$bin\stun2.bin" --dpi-desync-fake-http="$bin\tls_clienthello_sochi_park.bin" --new
--filter-udp=443 --ipset="$lists\ipset-all.txt" --hostlist-exclude="$lists\list-exclude.txt" --hostlist-exclude="$lists\list-exclude-user.txt" --ipset-exclude="$lists\ipset-exclude.txt" --ipset-exclude="$lists\ipset-exclude-user.txt" --dpi-desync=fake --dpi-desync-repeats=11 --dpi-desync-fake-quic="$bin\quic_initial_www_google_com.bin" --new
--filter-tcp=80,443,8443 --ipset="$lists\ipset-all.txt" --hostlist-exclude="$lists\list-exclude.txt" --hostlist-exclude="$lists\list-exclude-user.txt" --ipset-exclude="$lists\ipset-exclude.txt" --ipset-exclude="$lists\ipset-exclude-user.txt" --dpi-desync=fake,hostfakesplit --dpi-desync-fooling=ts --dpi-desync-hostfakesplit-mod=host=mail.ru,altorder=1 --dpi-desync-repeats=5 --dpi-desync-fake-tls="$bin\tls_clienthello_sochi_park.bin" --dpi-desync-fake-tls="$bin\stun2.bin" --dpi-desync-fake-http="$bin\tls_clienthello_sochi_park.bin" --new
--filter-tcp=$($gf.Tcp) --ipset="$lists\ipset-all.txt" --ipset-exclude="$lists\ipset-exclude.txt" --ipset-exclude="$lists\ipset-exclude-user.txt" --dpi-desync=fake,hostfakesplit --dpi-desync-any-protocol=1 --dpi-desync-cutoff=n4 --dpi-desync-fooling=ts --dpi-desync-hostfakesplit-mod=host=mail.ru,altorder=1 --dpi-desync-repeats=5 --dpi-desync-fake-tls="$bin\tls_clienthello_sochi_park.bin" --dpi-desync-fake-tls="$bin\stun2.bin" --dpi-desync-fake-http="$bin\tls_clienthello_sochi_park.bin" --dpi-desync-fake-unknown="$bin\tls_clienthello_sochi_park.bin" --dpi-desync-fake-unknown="$bin\stun2.bin" --new
--filter-udp=$($gf.Udp) --ipset="$lists\ipset-all.txt" --ipset-exclude="$lists\ipset-exclude.txt" --ipset-exclude="$lists\ipset-exclude-user.txt" --dpi-desync=fake --dpi-desync-repeats=10 --dpi-desync-any-protocol=1 --dpi-desync-fake-unknown-udp="$bin\ACTIVE_GAME_UDP.bin" --dpi-desync-cutoff=n4
"@
Start-ZapretWinws -ArgumentList $argList
