# Zapret Manager: UI language and strings (RU / EN).

Set-StrictMode -Version Latest

$script:ZapmanUiLang = 'en'

$script:ZapmanUiEn = @{
    AppName              = 'Zapret Manager'
    AppTitle             = 'Zapret Manager {0}'
    LangRu               = 'RU'
    LangEn               = 'EN'
    GrpStatus            = 'Status'
    GrpSettings          = 'Settings'
    GrpTools             = 'Tools'
    BtnStart             = 'Start service'
    BtnStop              = 'Stop'
    BtnRemove            = 'Remove services'
    BtnStrategy          = 'Strategy...'
    BtnFakes             = 'Fakes...'
    BtnIpset             = 'Download ipset'
    BtnHosts             = 'Compare hosts'
    BtnVersion           = 'Check version'
    BtnDiag              = 'Diagnostics'
    BtnRunSelected       = 'Run without installing'
    BtnInstall           = 'Install service'
    BtnTests             = 'Run tests'
    BtnStratNone         = 'None work?'
    BtnCopy              = 'Copy'
    BtnClose             = 'Close'
    BtnOk                = 'OK'
    BtnCancel            = 'Cancel'
    ChkAuto              = 'Auto-Update Check'
    ChkTray              = 'Tray icon'
    LblGame              = 'Game Filter'
    LblIpset             = 'IPSet Filter'
    LblEngine            = 'Engine'
    EngineNoFlags        = 'This strategy has no {0} flags.'
    EngineNoWinws        = 'winws.exe is not found in the bin folder.'
    EngineNoWinws2       = 'winws2.exe or bin\lua is not found. Add the zapret2 files to bin.'
    EngineStartFail      = '{0} did not start. Check the bin folder and antivirus exclusions.'
    EngineInstallFail    = '{0} did not start. The service was not installed.'
    EngineServiceFail    = 'The service started, but {0} is not running.'
    EngineCmdFail        = 'Failed to read the {0} command line.'
    BannerLastError      = 'The engine did not start. Click Status for the full error.'
    StratTitle           = 'Strategy'
    StratNoneConfirm     = 'Reset Winsock, IP, WinHTTP proxy and DNS? Restart Windows after this.'
    StratNoneDone        = 'Reset finished.'
    StratNoneDoneReboot  = 'Reset finished. Restart Windows now?'
    StratNoneRebootLater = 'Restart Windows to finish the reset.'
    StratNoneFail        = 'Reset failed. See the log.'
    StatusDlgTitle       = 'Status and journal'
    JournalHeader        = 'Journal'
    StatusBypassOn       = 'Bypass: running ({0})'
    StatusBypassOff      = 'Bypass: not running'
    StatusServiceOn      = 'Service: installed ({0})'
    StatusServiceOff     = 'Service: not installed'
    StatusStrategy       = 'Strategy: {0}'
    StatusStrategyNone   = 'Strategy: -'
    StatusStrategyGone   = 'Strategy: {0} (no files in strategies/)'
    StatusStrategyManual = 'Strategy: - (manual run)'
    StatusStrategyRun    = 'Strategy: {0} (manual run)'
    StatusDivertOn       = 'WinDivert: running'
    StatusDivertPending  = 'WinDivert: STOP_PENDING'
    StatusDivertOther    = 'WinDivert: {0}'
    StatusDivertNone     = 'WinDivert: not installed'
    BannerNoService      = 'No service. Start a strategy from Strategy..., or install one for autostart.'
    BannerMismatch       = 'Service is installed, {0} is not running. Use Start service.'
    BannerOrphan         = 'Bypass is running from Strategy..., without autostart.'
    BannerNoStrategies   = 'No JSON files in strategies. Strategy... is unavailable. You can still start the installed service.'
    BannerStopPending    = 'WinDivert is STOP_PENDING. Remove services (reboot if it stays). Do not install over this.'
    TipStart             = 'Start the installed zapret service.'
    TipStop              = 'Stop winws / winws2 and the zapret service if it is running.'
    TipRemove            = 'Remove zapret and WinDivert services. No extra confirmation.'
    TipStrategy          = 'Pick a strategy: install as a service, run without installing, or run tests.'
    TipStratNone         = 'Reset Winsock, IP, WinHTTP proxy and DNS. Restart Windows after.'
    TipFakes             = 'Current Discord UDP and Game UDP fake files in bin.'
    TipIpset             = 'Download ipset-all.txt from the repository.'
    TipHosts             = 'Compare Windows hosts with the repo copy. If they differ, copy the template or open hosts in Notepad.'
    TipVersion           = 'Compare this build tag with GitHub tags. Does not download a new archive.'
    TipDiag              = 'Check conflicts, path, DNS, WinDivert and Discord cache.'
    TipAuto              = 'When enabled, the GUI checks the app version at start. The check does not block the window.'
    TipTray              = 'When enabled, a tray icon starts at logon. Use it to open the GUI and to start or stop the service. Clear the box to remove the icon and the logon task.'
    TipStatusClick       = 'Click for full status, last error, WinDivert64.sys and the action journal.'
    ConfirmRunOver       = 'Stop the running service or bypass, then run this strategy without installing?'
    FilterNeedInstall    = 'Game Filter is saved. Install the service again to apply it?'
    FilterNeedRestart    = 'IPSet Filter is saved. Stop, then start the service to apply it?'
    FilterNeedRerun      = 'Filter is saved. Stop, then run a strategy from Strategy... to apply it.'
    GameHintInstall      = 'Game Filter saved. Run Install Service again to apply.'
    GameHintRerun        = 'Game Filter saved. Stop, then run without installing to apply.'
    IpsetHintRestart     = 'IPSet Filter saved. Stop, then Start service to apply.'
    IpsetHintRerun       = 'IPSet Filter saved. Stop, then run without installing to apply.'
    FakeNeedRestart      = 'Fakes are saved. Stop, then start the service to apply them?'
    FakeNeedRerun        = 'Fakes are saved. Stop, then run a strategy from Strategy... to apply them.'
    AdminRequired        = 'Administrator rights are required.'
    BinMissing           = 'The bin folder is not found. Extract the full Zapret archive first.'
    NoStrategies         = 'No strategy files found in the strategies folder.'
    TestsNeedNoService   = 'The zapret service will be removed for the test run, then installed again.'
    TestsCancelled       = 'Tests cancelled.'
    TestsFinished        = 'Tests finished.'
    TestsTitle           = 'Tests'
    TestsSetupTitle      = 'Run Tests'
    TestsType            = 'Test type'
    TestsTypeStd         = 'Standard (HTTP / ping)'
    TestsTypeDpi         = 'DPI checkers (TCP 16-20)'
    TestsPick            = 'Strategies to test ({0})'
    TestsAll             = 'All'
    TestsNone            = 'None'
    TestsStart           = 'Start tests'
    TestsNeedOne         = 'Select at least one strategy.'
    TestsStarting        = 'Starting tests...'
    TestsProgress        = 'Testing {0} / {1}'
    TestsCancelling      = 'Cancelling...'
    TestsCancelledShort  = 'Cancelled.'
    TestsFinishedLog     = 'Tests finished. See test-results\ for the saved log.'
    TestsGrpHead         = 'Setup'
    TestsGrpStrats       = 'Strategies'
    TestsGrpSum          = 'Summary'
    TestsWaitStrat       = 'Waiting for the first strategy...'
    TestsColTarget       = 'Target'
    TestsColPing         = 'Ping'
    TestsBest            = 'Best: {0}'
    TestsSumOk           = 'OK'
    TestsSumErr          = 'ERR'
    TestsSumUnsup        = 'UNSUP'
    TestsSumFail         = 'FAIL'
    TestsSumBlocked      = 'BLOCKED'
    TestsSumPingOk       = 'Ping OK'
    TestsSumPingFail     = 'Ping fail'
    DownloadConnecting   = 'Connecting...'
    DownloadProgress     = 'Downloaded {0} of {1} KB ({2}%)'
    DownloadProgressKb   = 'Downloaded {0} KB'
    DownloadCancelled    = 'Download cancelled.'
    DownloadFailed       = 'Download failed.'
    StatusLineRunning    = 'Running strategy: {0}'
    StatusLineService    = 'Service strategy: {0}'
    StatusLineSvcRun     = '{0} service is RUNNING.'
    StatusLineSvcPending = '{0} is STOP_PENDING. Run Diagnostics to look for a conflict.'
    StatusLineSvcOff     = '{0} service is NOT running.'
    StatusLineSysMissing = 'WinDivert64.sys file NOT found.'
    StatusLineBypassOn   = 'Bypass ({0}) is RUNNING.'
    StatusLineBypassOff  = 'Bypass (winws / winws2) is NOT running.'
    StatusLineLastError  = 'Last error:'
    ConfigParseFail      = 'config.json is not valid JSON. Using defaults.'
    FakesTitle           = 'Fakes'
    FakesDiscord         = 'Discord UDP'
    FakesGame            = 'Game UDP'
    FakesMissing         = '(not found)'
    FakesUnlisted        = '(not in list)'
    FakesPick            = '{0} file number (0 = keep)'
    FakesNone            = 'No .bin files were found in the bin folder.'
    StratMarkRun         = ' (running)'
    StratMarkService     = ' (service)'
    VersionNew           = 'New version available: {0}. Open the releases page?'
    VersionLatest        = 'Latest version installed: {0}'
    VersionFail          = 'Failed to fetch the latest version. This warning does not affect zapret.'
    VersionChecking      = 'Checking version...'
    AutoFail             = 'Version check failed. Zapret still works.'
    HostsTitle           = 'Compare hosts'
    HostsNeed            = 'The hosts file needs an update. Copy the template, open hosts, paste the block at the end (or replace the old one), then save.'
    HostsCopied          = 'Template copied.'
    HostsOk              = 'Hosts file is up to date.'
    HostsFail            = 'Failed to download hosts file from the repository.'
    HostsCancel          = 'Hosts compare cancelled.'
    BtnHostsCopy         = 'Copy template'
    BtnHostsOpen         = 'Open hosts'
    TipHostsCopy         = 'Copy the repository hosts block to the clipboard.'
    TipHostsOpen         = 'Open the Windows hosts file in Notepad. You can save it (the app is elevated).'
    IpsetTitle           = 'Download ipset'
    IpsetOk              = 'IPSet list updated.'
    IpsetCancel          = 'IPSet download cancelled.'
    DiagTitle            = 'Diagnostics'
    DiagConflicts        = 'Remove these conflicting services?'
    DiagCache            = 'Clear Discord cache (Stable, PTB, Canary, Development)?'
    DiagRun              = 'Run'
    DiagDone             = 'Diagnostics finished.'
    RemoveDone           = 'Services removed.'
    StopDone             = 'Stopped.'
    StartDone            = 'Service started.'
    StartDoneName        = 'Started service ({0}).'
    RunDone              = 'Running {0} (not installed as a service).'
    InstallDone          = 'Installed service: {0}.'
    FakeDone             = 'Replaced {0} fake with {1}.'
    MenuStrategy         = 'Strategy (run / install / tests)'
    MenuStart            = 'Start service'
    MenuStop             = 'Stop'
    MenuRemove           = 'Remove services'
    MenuStatus           = 'Status'
    MenuGame             = 'Game Filter'
    MenuIpset            = 'IPSet Filter'
    MenuAuto             = 'Auto-Update Check'
    MenuTray             = 'Tray icon'
    MenuFakes            = 'Fakes'
    MenuIpsetDl          = 'Download ipset'
    MenuHosts            = 'Compare hosts'
    MenuVersion          = 'Check version'
    MenuDiag             = 'Diagnostics'
    MenuExit             = 'Exit'
    PickStrategy         = 'Pick a strategy:'
    CancelItem           = '0. Cancel'
    InvalidChoice        = 'Invalid choice.'
    IpsetNow             = 'IPSet Filter is now: {0}'
    AutoOn               = 'Auto-Update Check enabled.'
    AutoOff              = 'Auto-Update Check disabled.'
    TrayOn               = 'Tray icon enabled.'
    TrayOff              = 'Tray icon disabled.'
    TrayOpen             = 'Open'
    TrayStart            = 'Start service'
    TrayStop             = 'Stop'
    ConsoleUtf8Warn      = 'Console UTF-8 may not display all characters on this system.'
    CliTitle             = 'Zapret Manager CLI'
    CliService           = 'Service manager'
    CliTests             = 'Strategy tests'
    CliEnv               = 'Check environment'
    CliUnknown           = 'Unknown command: {0}'
    CliUsage             = "cli.bat`r`ncli.bat service`r`ncli.bat tests [-TestType standard|dpi] [-Strategies all|name,...] [-NoPause]`r`ncli.bat env"
}

$script:ZapmanUiRu = @{
    AppName              = 'Zapret Manager'
    AppTitle             = 'Zapret Manager {0}'
    LangRu               = 'RU'
    LangEn               = 'EN'
    GrpStatus            = 'Status'
    GrpSettings          = 'Settings'
    GrpTools             = 'Tools'
    BtnStart             = 'Старт службы'
    BtnStop              = 'Стоп'
    BtnRemove            = 'Снять службы'
    BtnStrategy          = 'Стратегия...'
    BtnFakes             = 'Fake...'
    BtnIpset             = 'Скачать ipset'
    BtnHosts             = 'Сверить hosts'
    BtnVersion           = 'Проверить версию'
    BtnDiag              = 'Диагностика'
    BtnRunSelected       = 'Запустить без установки'
    BtnInstall           = 'Установить службу'
    BtnTests             = 'Прогнать тесты'
    BtnStratNone         = 'Ни одна не подходит'
    BtnCopy              = 'Копировать'
    BtnClose             = 'Закрыть'
    BtnOk                = 'OK'
    BtnCancel            = 'Отмена'
    ChkAuto              = 'Auto-Update Check'
    ChkTray              = 'Иконка в трее'
    LblGame              = 'Game Filter'
    LblIpset             = 'IPSet Filter'
    LblEngine            = 'Движок'
    EngineNoFlags        = 'У этой стратегии нет флагов {0}.'
    EngineNoWinws        = 'winws.exe не найден в папке bin.'
    EngineNoWinws2       = 'Нет winws2.exe или bin\lua. Положите файлы zapret2 в bin.'
    EngineStartFail      = '{0} не запустился. Проверьте папку bin и исключения антивируса.'
    EngineInstallFail    = '{0} не запустился. Служба не установлена.'
    EngineServiceFail    = 'Служба стартовала, но {0} не запущен.'
    EngineCmdFail        = 'Не удалось прочитать командную строку {0}.'
    BannerLastError      = 'Движок не запустился. Полный текст — клик по Status.'
    StratTitle           = 'Стратегия'
    StratNoneConfirm     = 'Сбросить Winsock, IP, WinHTTP-прокси и DNS? После этого перезагрузите Windows.'
    StratNoneDone        = 'Сброс выполнен.'
    StratNoneDoneReboot  = 'Сброс выполнен. Перезагрузить Windows сейчас?'
    StratNoneRebootLater = 'Перезагрузите Windows, чтобы закончить сброс.'
    StratNoneFail        = 'Сброс не удался. См. журнал.'
    StatusDlgTitle       = 'Статус и журнал'
    JournalHeader        = 'Журнал'
    StatusBypassOn       = 'Обход: работает ({0})'
    StatusBypassOff      = 'Обход: не запущен'
    StatusServiceOn      = 'Служба: установлена ({0})'
    StatusServiceOff     = 'Служба: не установлена'
    StatusStrategy       = 'Стратегия: {0}'
    StatusStrategyNone   = 'Стратегия: -'
    StatusStrategyGone   = 'Стратегия: {0} (нет файлов в strategies/)'
    StatusStrategyManual = 'Стратегия: - (ручной запуск)'
    StatusStrategyRun    = 'Стратегия: {0} (ручной запуск)'
    StatusDivertOn       = 'WinDivert: running'
    StatusDivertPending  = 'WinDivert: STOP_PENDING'
    StatusDivertOther    = 'WinDivert: {0}'
    StatusDivertNone     = 'WinDivert: not installed'
    BannerNoService      = 'Службы нет. Запуск/установка — через «Стратегия...».'
    BannerMismatch       = 'Служба стоит, процесс {0} не запущен. Нажмите «Старт службы».'
    BannerOrphan         = 'Обход запущен из «Стратегия...», без автозапуска.'
    BannerNoStrategies   = 'В папке strategies нет .json. «Стратегия...» недоступна. Старт службы ещё можно.'
    BannerStopPending    = 'WinDivert завис (STOP_PENDING). Снимите службы, перезагрузка если не отпускает. Не ставьте службу поверх.'
    TipStart             = 'Запустить установленную службу zapret.'
    TipStop              = 'Остановить winws / winws2 и службу zapret, если она запущена.'
    TipRemove            = 'Снять службы zapret и WinDivert. Без дополнительного вопроса.'
    TipStrategy          = 'Выбрать стратегию: поставить службу, запустить без установки или прогнать тесты.'
    TipStratNone         = 'Сброс Winsock, IP, WinHTTP-прокси и DNS. После этого перезагрузите Windows.'
    TipFakes             = 'Текущие fake Discord UDP и Game UDP в bin.'
    TipIpset             = 'Скачать ipset-all.txt из репозитория.'
    TipHosts             = 'Сравнить hosts Windows с копией из репозитория. При расхождении можно скопировать шаблон или открыть hosts в Блокноте.'
    TipVersion           = 'Сравнить тег этой сборки с тегами GitHub. Архив сами не скачивает.'
    TipDiag              = 'Конфликты, путь, DNS, WinDivert и кэш Discord.'
    TipAuto              = 'Если включено, GUI сверяет версию при старте. Проверка не блокирует окно.'
    TipTray              = 'Если включено, иконка в трее появляется при входе. Из трея: открыть GUI, старт службы, стоп. Снимите галку, чтобы убрать иконку и задание.'
    TipStatusClick       = 'Клик — полный статус, последняя ошибка, WinDivert64.sys и журнал действий.'
    ConfirmRunOver       = 'Остановить службу или процесс обхода и запустить эту стратегию без установки?'
    FilterNeedInstall    = 'Game Filter сохранён. Поставить службу снова, чтобы применить?'
    FilterNeedRestart    = 'IPSet Filter сохранён. Остановить и снова запустить службу, чтобы применить?'
    FilterNeedRerun      = 'Фильтр сохранён. Стоп, затем запуск из «Стратегия...», чтобы применить.'
    GameHintInstall      = 'Game Filter сохранён. Поставьте службу снова, чтобы применить.'
    GameHintRerun        = 'Game Filter сохранён. Стоп, затем запуск без установки.'
    IpsetHintRestart     = 'IPSet Filter сохранён. Стоп, затем старт службы, чтобы применить.'
    IpsetHintRerun       = 'IPSet Filter сохранён. Стоп, затем запуск без установки.'
    FakeNeedRestart      = 'Fake сохранены. Остановить и снова запустить службу, чтобы применить?'
    FakeNeedRerun        = 'Fake сохранены. Стоп, затем запуск из «Стратегия...», чтобы применить.'
    AdminRequired        = 'Нужны права администратора.'
    BinMissing           = 'Папка bin не найдена. Сначала распакуйте полный архив Zapret.'
    NoStrategies         = 'В папке strategies нет файлов стратегий.'
    TestsNeedNoService   = 'Служба zapret будет снята на время тестов, затем поставлена снова.'
    TestsCancelled       = 'Тесты отменены.'
    TestsFinished        = 'Тесты закончены.'
    TestsTitle           = 'Тесты'
    TestsSetupTitle      = 'Прогнать тесты'
    TestsType            = 'Тип теста'
    TestsTypeStd         = 'Обычный (HTTP / ping)'
    TestsTypeDpi         = 'DPI-проверки (TCP 16-20)'
    TestsPick            = 'Стратегии для теста ({0})'
    TestsAll             = 'Все'
    TestsNone            = 'Нет'
    TestsStart           = 'Начать тесты'
    TestsNeedOne         = 'Выберите хотя бы одну стратегию.'
    TestsStarting        = 'Запуск тестов...'
    TestsProgress        = 'Тест {0} / {1}'
    TestsCancelling      = 'Отмена...'
    TestsCancelledShort  = 'Отменено.'
    TestsFinishedLog     = 'Тесты закончены. Лог в test-results\.'
    TestsGrpHead         = 'Подготовка'
    TestsGrpStrats       = 'Стратегии'
    TestsGrpSum          = 'Итоги'
    TestsWaitStrat       = 'Ждём первую стратегию...'
    TestsColTarget       = 'Цель'
    TestsColPing         = 'Ping'
    TestsBest            = 'Лучшая: {0}'
    TestsSumOk           = 'OK'
    TestsSumErr          = 'ERR'
    TestsSumUnsup        = 'UNSUP'
    TestsSumFail         = 'FAIL'
    TestsSumBlocked      = 'BLOCKED'
    TestsSumPingOk       = 'Ping OK'
    TestsSumPingFail     = 'Ping fail'
    DownloadConnecting   = 'Подключение...'
    DownloadProgress     = 'Скачано {0} из {1} КБ ({2}%)'
    DownloadProgressKb   = 'Скачано {0} КБ'
    DownloadCancelled    = 'Загрузка отменена.'
    DownloadFailed       = 'Загрузка не удалась.'
    StatusLineRunning    = 'Запущенная стратегия: {0}'
    StatusLineService    = 'Стратегия службы: {0}'
    StatusLineSvcRun     = 'Служба {0} запущена.'
    StatusLineSvcPending = '{0} в STOP_PENDING. Диагностика может показать конфликт.'
    StatusLineSvcOff     = 'Служба {0} не запущена.'
    StatusLineSysMissing = 'Файл WinDivert64.sys не найден.'
    StatusLineBypassOn   = 'Обход ({0}) запущен.'
    StatusLineBypassOff  = 'Обход (winws / winws2) не запущен.'
    StatusLineLastError  = 'Последняя ошибка:'
    ConfigParseFail      = 'config.json не JSON. Используются значения по умолчанию.'
    FakesTitle           = 'Fake'
    FakesDiscord         = 'Discord UDP'
    FakesGame            = 'Game UDP'
    FakesMissing         = '(нет файла)'
    FakesUnlisted        = '(не из списка)'
    FakesPick            = '{0}: номер файла (0 — оставить)'
    FakesNone            = 'В папке bin нет файлов .bin.'
    StratMarkRun         = ' (запущена)'
    StratMarkService     = ' (служба)'
    VersionNew           = 'Доступна новая версия: {0}. Открыть страницу релизов?'
    VersionLatest        = 'Установлена последняя версия: {0}'
    VersionFail          = 'Не удалось получить последнюю версию. На работу zapret это не влияет.'
    VersionChecking      = 'Проверка версии...'
    AutoFail             = 'Проверка версии не удалась. Zapret продолжает работать.'
    HostsTitle           = 'Сверить hosts'
    HostsNeed            = 'Файл hosts нужно обновить. Скопируйте шаблон, откройте hosts, вставьте блок в конец (или замените прежний) и сохраните.'
    HostsCopied          = 'Шаблон скопирован.'
    HostsOk              = 'Файл hosts актуален.'
    HostsFail            = 'Не удалось скачать hosts из репозитория.'
    HostsCancel          = 'Сверка hosts отменена.'
    BtnHostsCopy         = 'Копировать шаблон'
    BtnHostsOpen         = 'Открыть hosts'
    TipHostsCopy         = 'Скопировать блок hosts из репозитория в буфер.'
    TipHostsOpen         = 'Открыть системный hosts в Блокноте. Можно сохранить: приложение уже с правами администратора.'
    IpsetTitle           = 'Скачать ipset'
    IpsetOk              = 'Список IPSet обновлён.'
    IpsetCancel          = 'Загрузка IPSet отменена.'
    DiagTitle            = 'Диагностика'
    DiagConflicts        = 'Снять эти конфликтующие службы?'
    DiagCache            = 'Очистить кэш Discord (Stable, PTB, Canary, Development)?'
    DiagRun              = 'Запуск'
    DiagDone             = 'Диагностика закончена.'
    RemoveDone           = 'Службы сняты.'
    StopDone             = 'Остановлено.'
    StartDone            = 'Служба запущена.'
    StartDoneName        = 'Запущена служба ({0}).'
    RunDone              = 'Запущено {0} (не как служба).'
    InstallDone          = 'Установлена служба: {0}.'
    FakeDone             = 'Слот {0} заменён на {1}.'
    MenuStrategy         = 'Стратегия (запуск / установка / тесты)'
    MenuStart            = 'Старт службы'
    MenuStop             = 'Стоп'
    MenuRemove           = 'Снять службы'
    MenuStatus           = 'Статус'
    MenuGame             = 'Game Filter'
    MenuIpset            = 'IPSet Filter'
    MenuAuto             = 'Auto-Update Check'
    MenuTray             = 'Иконка в трее'
    MenuFakes            = 'Fake'
    MenuIpsetDl          = 'Скачать ipset'
    MenuHosts            = 'Сверить hosts'
    MenuVersion          = 'Проверить версию'
    MenuDiag             = 'Диагностика'
    MenuExit             = 'Выход'
    PickStrategy         = 'Выберите стратегию:'
    CancelItem           = '0. Отмена'
    InvalidChoice        = 'Неверный выбор.'
    IpsetNow             = 'IPSet Filter сейчас: {0}'
    AutoOn               = 'Auto-Update Check включён.'
    AutoOff              = 'Auto-Update Check выключен.'
    TrayOn               = 'Иконка в трее включена.'
    TrayOff              = 'Иконка в трее выключена.'
    TrayOpen             = 'Открыть'
    TrayStart            = 'Старт службы'
    TrayStop             = 'Стоп'
    ConsoleUtf8Warn      = 'UTF-8 в консоли на этой системе может отображаться не полностью.'
    CliTitle             = 'Zapret Manager CLI'
    CliService           = 'Менеджер службы'
    CliTests             = 'Тесты стратегий'
    CliEnv               = 'Проверить среду'
    CliUnknown           = 'Неизвестная команда: {0}'
    CliUsage             = "cli.bat`r`ncli.bat service`r`ncli.bat tests [-TestType standard|dpi] [-Strategies all|name,...] [-NoPause]`r`ncli.bat env"
}

function Test-ZapmanUiLanguageCode {
    param([string]$Code)
    if ($Code -eq 'ru' -or $Code -eq 'en') {
        return $true
    }
    return $false
}

function Get-ZapmanUiLanguageFromOs {
    $ui = [string]$PSUICulture
    if ([string]::IsNullOrWhiteSpace($ui)) {
        $ui = [System.Globalization.CultureInfo]::CurrentUICulture.Name
    }
    if ($ui -like 'ru*') {
        return 'ru'
    }
    return 'en'
}

function Initialize-ZapmanUiLanguage {
    $fromCfg = ''
    $cfgPath = Get-ZapmanConfigPath
    if (Test-Path -LiteralPath $cfgPath) {
        try {
            $raw = [System.IO.File]::ReadAllText($cfgPath)
            if ($raw -match '"language"\s*:\s*"(ru|en)"') {
                $fromCfg = $Matches[1]
            }
        } catch {
            $fromCfg = ''
        }
    }
    if (Test-ZapmanUiLanguageCode $fromCfg) {
        $script:ZapmanUiLang = $fromCfg
        return $script:ZapmanUiLang
    }
    $script:ZapmanUiLang = Get-ZapmanUiLanguageFromOs
    return $script:ZapmanUiLang
}

function Get-ZapmanUiLanguage {
    return $script:ZapmanUiLang
}

function Set-ZapmanUiLanguage {
    param([string]$Language)
    $code = ([string]$Language).Trim().ToLowerInvariant()
    if (-not (Test-ZapmanUiLanguageCode $code)) {
        throw 'UI language must be ru or en.'
    }
    $script:ZapmanUiLang = $code
    [void](Update-ZapmanConfig -Language $code)
}

function Get-ZapmanUiString {
    param(
        [Parameter(Mandatory = $true)]
        [string]$Key,
        [object[]]$FormatArgs = @()
    )
    $table = $script:ZapmanUiEn
    if ($script:ZapmanUiLang -eq 'ru') {
        $table = $script:ZapmanUiRu
    }
    $text = ''
    if ($table.ContainsKey($Key)) {
        $text = [string]$table[$Key]
    } elseif ($script:ZapmanUiEn.ContainsKey($Key)) {
        $text = [string]$script:ZapmanUiEn[$Key]
    } else {
        $text = $Key
    }
    $argsList = @($FormatArgs)
    if ($argsList.Count -gt 0) {
        return ($text -f $argsList)
    }
    return $text
}

function Enable-ZapmanConsoleUtf8 {
    try {
        [Console]::OutputEncoding = [System.Text.Encoding]::UTF8
        [Console]::InputEncoding = [System.Text.Encoding]::UTF8
        $OutputEncoding = [System.Text.Encoding]::UTF8
    } catch {
        return
    }
}
