@{
    RootModule        = 'Zapman.psm1'
    ModuleVersion     = '1.10.2'
    GUID              = 'b7ec8669-6f32-4d4b-8a21-9c8d7e6f5a43'
    Author            = 'Zapret Manager'
    Description       = 'Zapret Manager helpers for the GUI, console, strategies and tests. Load this module by path. Engine helpers stay in src/Zapret.'
    PowerShellVersion = '3.0'
    FunctionsToExport = @(
        'Get-ZapretLayout'
        'Get-ZapmanConfig'
        'Get-ZapmanConfigError'
        'Get-ZapmanLocalVersion'
        'Initialize-ZapmanUserLists'
        'Test-ZapmanHostReady'
        'Test-ZapretBinVersions'
        'Show-ZapmanHostReadyReport'
        'Test-ZapmanTcpTimestampsEnabled'
        'Enable-ZapmanTcpTimestamps'
        'Enable-ZapmanTls12'
        'Get-ZapretEngine'
        'Set-ZapretEngine'
        'Get-ZapretEngineExeName'
        'Test-ZapretEngineFiles'
        'Test-ZapretStrategySupportsEngine'
        'Get-ZapretGameFilter'
        'Set-ZapretGameFilterMode'
        'Test-ZapretServiceRunning'
        'Test-ZapretNamedService'
        'Get-ZapretService'
        'Invoke-ZapretStrategyPrep'
        'Get-ZapretStrategyFiles'
        'Start-ZapretWinws'
        'Start-ZapretStrategyFile'
        'ConvertTo-ZapretServiceImagePath'
        'Test-ZapretBypassRunning'
        'Get-ZapretStatusBypassName'
        'Get-ZapretInstalledStrategyName'
        'Get-ZapretRunningStrategyName'
        'Get-ZapretIpsetStatus'
        'Set-ZapretIpsetMode'
        'Stop-ZapretWinwsProcess'
        'Wait-ZapretServiceStopped'
        'Wait-ZapretServiceGone'
        'Stop-ZapretBypass'
        'Wait-ZapretWinws'
        'Get-ZapretWinwsCommandLine'
        'Remove-ZapretServiceRecord'
        'Suspend-ZapretServiceForTests'
        'Restore-ZapretServiceAfterTests'
        'Start-ZapretSelectedStrategy'
        'Start-ZapretServiceIfInstalled'
        'Install-ZapretService'
        'Remove-ZapretServices'
        'Test-ZapmanAutoUpdateEnabled'
        'Set-ZapmanAutoUpdateEnabled'
        'Get-ZapretVersionCheckUrl'
        'Get-ZapretRemoteVersion'
        'Get-ZapretReleasePageUrl'
        'Get-ZapretIpsetListUrl'
        'Get-ZapretHostsSourceUrl'
        'Invoke-ZapmanWebDownload'
        'Update-ZapretIpsetList'
        'Get-ZapretHostsUpdateInfo'
        'Open-ZapretHostsUpdate'
        'Get-ZapretFakeCatalog'
        'Get-ZapretFakeCurrentText'
        'Set-ZapretActiveFake'
        'Invoke-ZapmanStrategyTests'
        'Get-ZapmanStatusLines'
        'Clear-ZapmanDiscordCache'
        'Remove-ZapretNamedServices'
        'Get-ZapmanDiagnosticReport'
        'Invoke-ZapmanDiagnosticAction'
        'Initialize-ZapmanUiLanguage'
        'Get-ZapmanUiLanguage'
        'Set-ZapmanUiLanguage'
        'Get-ZapmanUiString'
        'Enable-ZapmanConsoleUtf8'
    )
    CmdletsToExport   = @()
    VariablesToExport = @()
    AliasesToExport   = @()
}
