name: Lint

on:
  push:
    branches: [main]
  pull_request:

jobs:
  powershell:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install PSScriptAnalyzer
        shell: powershell
        run: |
          Install-Module -Name PSScriptAnalyzer -Force -Scope CurrentUser -SkipPublisherCheck

      - name: Lint
        shell: cmd
        run: powershell.exe -NoProfile -STA -ExecutionPolicy Bypass -File dev\lint.ps1
