# Zapret local module. Load by path. Do not install this module in PSModulePath.

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Continue'

. (Join-Path $PSScriptRoot 'Core.ps1')
. (Join-Path $PSScriptRoot 'Ui.ps1')
. (Join-Path $PSScriptRoot 'Bypass.ps1')
. (Join-Path $PSScriptRoot 'Tools.ps1')
. (Join-Path $PSScriptRoot 'Tests.ps1')

Export-ModuleMember -Function @(
    'Get-ZapretLayout'
    'Get-ZapretConfig'
    'Get-ZapretLocalVersion'
    'Initialize-ZapretUserLists'
    'Test-ZapretHostReady'
    'Test-ZapretBinVersions'
    'Show-ZapretHostReadyReport'
    'Test-ZapretTcpTimestampsEnabled'
    'Enable-ZapretTcpTimestamps'
    'Enable-ZapretTls12'
    'Get-ZapretEngine'
    'Set-ZapretEngine'
    'Get-ZapretEngineExeName'
    'Test-ZapretEngineFiles'
    'Test-ZapretStrategySupportsEngine'
    'Get-ZapretGameFilter'
    'Set-ZapretGameFilterMode'
    'Test-ZapretServiceRunning'
    'Test-ZapretNamedService'
    'Get-ZapretService'
    'Invoke-ZapretStrategyPrep'
    'Get-ZapretStrategyFiles'
    'Start-ZapretWinws'
    'Start-ZapretStrategyFile'
    'ConvertTo-ZapretServiceImagePath'
    'Test-ZapretBypassRunning'
    'Get-ZapretStatusBypassName'
    'Get-ZapretInstalledStrategyName'
    'Get-ZapretRunningStrategyName'
    'Get-ZapretIpsetStatus'
    'Set-ZapretIpsetMode'
    'Stop-ZapretWinwsProcess'
    'Wait-ZapretServiceStopped'
    'Wait-ZapretServiceGone'
    'Stop-ZapretBypass'
    'Wait-ZapretWinws'
    'Get-ZapretWinwsCommandLine'
    'Remove-ZapretServiceRecord'
    'Start-ZapretSelectedStrategy'
    'Start-ZapretServiceIfInstalled'
    'Install-ZapretService'
    'Remove-ZapretServices'
    'Test-ZapretAutoUpdateEnabled'
    'Set-ZapretAutoUpdateEnabled'
    'Get-ZapretVersionCheckUrl'
    'Get-ZapretRemoteVersion'
    'Get-ZapretReleasePageUrl'
    'Get-ZapretIpsetListUrl'
    'Get-ZapretHostsSourceUrl'
    'Invoke-ZapretWebDownload'
    'Update-ZapretIpsetList'
    'Get-ZapretHostsUpdateInfo'
    'Open-ZapretHostsUpdate'
    'Get-ZapretFakeCatalog'
    'Set-ZapretActiveFake'
    'Start-ZapretConfigTests'
    'Invoke-ZapretStrategyTests'
    'Get-ZapretStatusLines'
    'Clear-ZapretDiscordCache'
    'Remove-ZapretNamedServices'
    'Get-ZapretDiagnosticReport'
    'Invoke-ZapretDiagnosticAction'
    'Initialize-ZapretUiLanguage'
    'Get-ZapretUiLanguage'
    'Set-ZapretUiLanguage'
    'Get-ZapretUiString'
    'Enable-ZapretConsoleUtf8'
)
