@{
    RootModule        = 'Zapret.psm1'
    ModuleVersion     = '1.10.2'
    GUID              = 'a6db7558-5e21-4c3a-9f10-8b7c6d5e4f32'
    Author            = 'zapret'
    Description       = 'Local Zapret helpers for the GUI, console manager, strategies and tests. Load this module by path.'
    PowerShellVersion = '3.0'
    FunctionsToExport = @(
        'Get-ZapretLayout'
        'Get-ZapretConfig'
        'Get-ZapretLocalVersion'
        'Initialize-ZapretUserLists'
        'Test-ZapretHostReady'
        'Test-ZapretBinVersions'
        'Show-ZapretHostReadyReport'
        'Test-ZapretTcpTimestampsEnabled'
        'Enable-ZapretTcpTimestamps'
        'Enable-ZapretTls12'
        'Get-ZapretEngine'
        'Set-ZapretEngine'
        'Get-ZapretEngineExeName'
        'Test-ZapretEngineFiles'
        'Test-ZapretStrategySupportsEngine'
        'Get-ZapretGameFilter'
        'Set-ZapretGameFilterMode'
        'Test-ZapretServiceRunning'
        'Test-ZapretNamedService'
        'Get-ZapretService'
        'Invoke-ZapretStrategyPrep'
        'Get-ZapretStrategyFiles'
        'Start-ZapretWinws'
        'Start-ZapretStrategyFile'
        'ConvertTo-ZapretServiceImagePath'
        'Test-ZapretBypassRunning'
        'Get-ZapretStatusBypassName'
        'Get-ZapretInstalledStrategyName'
        'Get-ZapretRunningStrategyName'
        'Get-ZapretIpsetStatus'
        'Set-ZapretIpsetMode'
        'Stop-ZapretWinwsProcess'
        'Wait-ZapretServiceStopped'
        'Wait-ZapretServiceGone'
        'Stop-ZapretBypass'
        'Wait-ZapretWinws'
        'Get-ZapretWinwsCommandLine'
        'Remove-ZapretServiceRecord'
        'Start-ZapretSelectedStrategy'
        'Start-ZapretServiceIfInstalled'
        'Install-ZapretService'
        'Remove-ZapretServices'
        'Test-ZapretAutoUpdateEnabled'
        'Set-ZapretAutoUpdateEnabled'
        'Get-ZapretVersionCheckUrl'
        'Get-ZapretRemoteVersion'
        'Get-ZapretReleasePageUrl'
        'Get-ZapretIpsetListUrl'
        'Get-ZapretHostsSourceUrl'
        'Invoke-ZapretWebDownload'
        'Update-ZapretIpsetList'
        'Get-ZapretHostsUpdateInfo'
        'Open-ZapretHostsUpdate'
        'Get-ZapretFakeCatalog'
        'Get-ZapretFakeCurrentText'
        'Set-ZapretActiveFake'
        'Start-ZapretConfigTests'
        'Invoke-ZapretStrategyTests'
        'Get-ZapretStatusLines'
        'Clear-ZapretDiscordCache'
        'Remove-ZapretNamedServices'
        'Get-ZapretDiagnosticReport'
        'Invoke-ZapretDiagnosticAction'
        'Initialize-ZapretUiLanguage'
        'Get-ZapretUiLanguage'
        'Set-ZapretUiLanguage'
        'Get-ZapretUiString'
        'Enable-ZapretConsoleUtf8'
    )
    CmdletsToExport   = @()
    VariablesToExport = @()
    AliasesToExport   = @()
}
